---
title: "R Notebook"
output: rmarkdown::github_document
---

```{r}
library(dplyr)
library(na.tools)
library(tidyimpute)


```

ss
```{r}
# Cargar el conjunto de datos

load("../data/01_datamanip/carIns_final.Rdata")
ls()

carIns_final

```
ss
```{r}
# Comprobar si hay valores faltantes en el conjunto de datos
missing_values <- sum(is.na(carIns_final))
if (missing_values > 0) {
  print("Hay valores faltantes en el conjunto de datos")
} else {
  print("No hay valores faltantes en el conjunto de datos")
}
```

ss
```{r}
library(dplyr)

# Verificar si hay algún valor faltante en cada fila
missing_cases <- carIns_final %>% 
  summarise(has_missing = anyNA(.))

# Contar el número de casos con al menos un valor faltante
num_missing_cases <- sum(missing_cases$has_missing)

# Imprimir el resultado
cat("Número de casos con al menos un valor faltante:", num_missing_cases, "\n")

# Contar el número de casos con al menos un valor faltante
num_missing_cases2 <- sum(is.na(carIns_final))

# Imprimir el resultado
cat("Número de casos con al menos un valor faltante:", num_missing_cases2, "\n")

```

